CREATE TABLE `urls` (
  `id` int NOT NULL AUTO_INCREMENT,
  `region` varchar(45) DEFAULT NULL,
  `url` TEXT NOT NULL,
  `date` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=281 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

